#!/bin/bash
# Generates the authoritative third-party license manifest for rclone.wasm.
#
# Why not `go-licenses`: it aborts on this build ("Package bytes does not have
# module info", google/go-licenses#128) because the js/wasm dependency graph is
# dominated by standard-library packages, which carry no module info. Both
# v1.6.0 and @latest fail identically, so the build cannot depend on it.
#
# Instead we ask the Go toolchain directly. `go list -deps` against the real
# GOOS=js GOARCH=wasm target enumerates exactly the packages linked into the
# binary — not what go.mod merely allows — and each package's module carries the
# resolved version and its module-cache directory, where the license file lives.
#
# Standard-library packages are intentionally excluded: they report no module
# and are covered as a whole by the Go BSD-3-Clause license in src/LICENSE-go.txt.
#
# A module is reported with every license its files carry, joined by " AND ",
# because several of them are genuinely multi-licensed: sigs.k8s.io/yaml ships
# MIT, BSD-3-Clause and Apache-2.0 in one LICENSE file, and gopkg.in/yaml.v3
# opens with "This project is covered by two different licenses: MIT and
# Apache." Reporting only the first match would name one license for a module
# that is distributed under three, in a document whose whole purpose is being
# exact about that.
#
# Usage: tools/gen-license-manifest.sh <package-dir> <output-file>
#
# MAIN_MODULE_VERSION (env, optional): version to record for the main module,
# which `go list` reports with an empty version. build-wasm.sh passes the
# pinned RCLONE_COMMIT so rclone's own row is not left blank.

set -e

PKG_DIR="${1:?usage: gen-license-manifest.sh <package-dir> <output-file>}"
OUT="${2:?usage: gen-license-manifest.sh <package-dir> <output-file>}"

# Prints every license detected in one license file, one SPDX id per line.
detect_license() {
    local f="$1"
    local -a found=()

    # CC0 and the Unlicense are public-domain dedications, and their full texts
    # quote permissive-license phrasing that would also trip the matchers below.
    # When either matches it is the entire license, so report it alone.
    if grep -qi "CC0 1.0" "$f" || grep -qi "Creative Commons Legal Code" "$f"; then
        echo "CC0-1.0"; return 0
    fi
    if grep -qi "This is free and unencumbered software released into the public domain" "$f"; then
        echo "Unlicense"; return 0
    fi

    # Every remaining matcher is independent: one file may contain several of
    # these license texts concatenated.
    if grep -qi "Apache License" "$f" && grep -q "Version 2.0" "$f"; then
        found+=("Apache-2.0")
    fi
    if grep -q "Permission is hereby granted, free of charge" "$f"; then
        found+=("MIT")
    fi
    if grep -q "Permission to use, copy, modify, and/or distribute" "$f"; then
        found+=("ISC")
    fi
    if grep -qi "Mozilla Public License" "$f"; then
        found+=("MPL-2.0")
    fi
    if grep -q "Redistribution and use" "$f"; then
        # The "no endorsement" clause is what separates 3-clause from 2-clause BSD.
        if grep -qi "Neither the name" "$f"; then
            found+=("BSD-3-Clause")
        else
            found+=("BSD-2-Clause")
        fi
    fi

    if [ ${#found[@]} -eq 0 ]; then
        echo "UNKNOWN"
    else
        printf '%s\n' "${found[@]}"
    fi
    return 0
}

# Unions the licenses of every license file a module ships — not just the first
# one found. go.yaml.in/yaml/v2, for example, carries both LICENSE and
# LICENSE.libyaml, and only reading one of them loses half the answer.
detect_module_licenses() {
    local dir="$1"
    local -a files=()
    local f
    while IFS= read -r f; do
        [ -f "$f" ] && files+=("$f")
    done < <(ls "$dir"/LICENSE* "$dir"/LICENCE* "$dir"/COPYING* "$dir"/License* 2>/dev/null || true)

    if [ ${#files[@]} -eq 0 ]; then
        echo "NOT-FOUND"
        return 0
    fi

    for f in "${files[@]}"; do
        detect_license "$f"
    done | sort -u | awk 'NR==1 {printf "%s", $0; next} {printf " AND %s", $0} END {print ""}'
}

# Resolve the output path before cd'ing into the package dir, so a relative one
# stays relative to where the caller ran the script rather than to $PKG_DIR.
case "$OUT" in
    /*) ;;
    *)  OUT="$PWD/$OUT" ;;
esac

cd "$PKG_DIR"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
GOOS=js GOARCH=wasm go list -deps \
    -f '{{if .Module}}{{.Module.Path}}|{{.Module.Version}}|{{.Module.Dir}}{{end}}' . \
    | sort -u | grep -v '^$' > "$TMP"

MODCOUNT=$(wc -l < "$TMP" | tr -d ' ')

{
    echo "Third-party Go modules linked into rclone.wasm"
    echo "==============================================="
    echo
    echo "Generated by tools/gen-license-manifest.sh — do not edit by hand."
    echo "Build target: GOOS=js GOARCH=wasm"
    echo "Modules: ${MODCOUNT}"
    echo
    echo "The Go standard library is not listed here: it carries no module info"
    echo "and is covered in full by the Go BSD-3-Clause license, reproduced in"
    echo "src/LICENSE-go.txt. Module license texts live in the Go module cache"
    echo "at the paths shown by 'go list -m -f {{.Dir}} <module>'."
    echo
    printf '%-62s %-24s %s\n' "MODULE" "VERSION" "LICENSE"
    printf '%-62s %-24s %s\n' "------" "-------" "-------"
} > "$OUT"

UNKNOWN=0
# Collect the classifications separately rather than re-parsing $OUT, whose
# prose header would otherwise be counted as license names in the totals.
LICLIST="$(mktemp)"
trap 'rm -f "$TMP" "$LICLIST"' EXIT

while IFS='|' read -r path version dir; do
    [ -z "$dir" ] && continue
    # `go list` reports no version for the main module (rclone itself), which
    # would leave the most important row in the manifest blank.
    if [ -z "$version" ]; then
        version="${MAIN_MODULE_VERSION:-(main module)}"
    fi
    lic="$(detect_module_licenses "$dir")"
    case "$lic" in
        *UNKNOWN*|*NOT-FOUND*) UNKNOWN=$((UNKNOWN + 1)) ;;
    esac
    echo "$lic" >> "$LICLIST"
    printf '%-62s %-24s %s\n' "$path" "$version" "$lic" >> "$OUT"
done < "$TMP"

{
    echo
    # Counted by license set, so a multi-licensed module is one entry under its
    # full combination rather than being split across the licenses it carries.
    echo "License totals (modules per license set):"
    sort "$LICLIST" | uniq -c | sort -rn | sed 's/^/  /'
} >> "$OUT"

echo "[*] Wrote $OUT (${MODCOUNT} modules)"
if [ "$UNKNOWN" -gt 0 ]; then
    echo "[!] ${UNKNOWN} module(s) could not be classified — review them before release."
fi
